name: graduacao
channels:
  - conda-forge
  - defaults
dependencies:
  - python >= 3.9
  - pip
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - openpyxl
  - xlrd
  - scikit-learn
  - rise
  - pip:
    - jupyter-contrib-nbextensions
    - tensorflow >= 2.0
